/**
 * TASK-45 — first-wallet onboarding wiring.
 *
 * Two contracts pinned here:
 *
 * 1. DR-11 carrier #1 — the quiz result reaches `SecuritySetup` as a
 *    `backupVerified` BOOLEAN route param. Verified => true, skip => false.
 *    Nothing else about the navigation payload changes (DR-9: the mnemonic
 *    handoff is an accepted risk being remediated in TASK-224 — this task must
 *    not widen it, so the param set is asserted exactly).
 *
 * 2. U-10 — a `beforeRemove` listener guards EVERY pop path (header back, iOS
 *    swipe-back, Android hardware back), not just the header button. Losing
 *    this screen destroys the only copy of the phrase.
 *
 * SECURITY NOTE: the phrase is generated by a mocked WalletService; no key
 * material is committed.
 */

import React from 'react';
import { render, fireEvent, act } from '@testing-library/react-native';

const MOCK_MNEMONIC =
  'abandon ability able abandon absent absorb abandon abstract';

jest.mock('@/services/wallet', () => ({
  WalletService: {
    generateWallet: jest.fn(() => ({ mnemonic: MOCK_MNEMONIC })),
  },
}));

jest.mock('@/contexts/ThemeContext', () => ({
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  useTheme: () => ({ theme: require('@/constants/themes').lightTheme }),
}));

jest.mock('@/hooks/useSecureScreen', () => ({ useSecureScreen: () => {} }));

jest.mock(
  '@expo/vector-icons',
  () => ({
    Ionicons: () => null,
  }),
  { virtual: true }
);

jest.mock('@/components/common/NFTBackground', () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { View } = require('react-native');
  return { NFTBackground: ({ children }: never) => <View>{children}</View> };
});

jest.mock('@/components/common/UniversalHeader', () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { Text, TouchableOpacity } = require('react-native');
  return {
    __esModule: true,
    default: ({ onBackPress }: { onBackPress: () => void }) => (
      <TouchableOpacity testID="header-back" onPress={onBackPress}>
        <Text>back</Text>
      </TouchableOpacity>
    ),
  };
});

jest.mock('@/components/wallet/MnemonicDisplay', () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { Text } = require('react-native');
  return {
    __esModule: true,
    default: ({ mnemonic }: { mnemonic: string }) => (
      <Text testID="mnemonic-display">{mnemonic}</Text>
    ),
  };
});

jest.mock('@/components/common/GlassButton', () => {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { Text, TouchableOpacity } = require('react-native');
  return {
    GlassButton: ({
      label,
      onPress,
    }: {
      label: string;
      onPress: () => void;
    }) => (
      <TouchableOpacity testID="saved-phrase-button" onPress={onPress}>
        <Text>{label}</Text>
      </TouchableOpacity>
    ),
  };
});

import { Alert } from 'react-native';
import CreateWalletScreen from '../CreateWalletScreen';

type Listener = (event: {
  preventDefault: () => void;
  data: { action: { type: string } };
}) => void;

function makeNavigation() {
  const listeners: Record<string, Listener[]> = {};
  return {
    navigate: jest.fn(),
    goBack: jest.fn(),
    dispatch: jest.fn(),
    addListener: jest.fn((event: string, cb: Listener) => {
      (listeners[event] ??= []).push(cb);
      return () => {
        listeners[event] = listeners[event].filter((l) => l !== cb);
      };
    }),
    /** Simulate any pop path (swipe-back, hardware back, header back). */
    emitBeforeRemove(): { prevented: boolean; action: { type: string } } {
      let prevented = false;
      const action = { type: 'POP' };
      listeners.beforeRemove?.forEach((cb) =>
        cb({
          preventDefault: () => {
            prevented = true;
          },
          data: { action },
        })
      );
      return { prevented, action };
    },
    hasBeforeRemoveListener: () => (listeners.beforeRemove ?? []).length > 0,
    /** Simulate this screen becoming active again (e.g. back from SecuritySetup). */
    emitFocus(): void {
      listeners.focus?.forEach((cb) => cb(undefined as never));
    },
  };
}

/**
 * Force the quiz onto a known target triple. `pickVerificationPositions` calls
 * `Math.floor(Math.random() * total)`, so feeding `pos / total` yields exactly
 * `pos`; the shuffle consumes whatever is left. The spy stays installed for the
 * whole test because the quiz only mounts after a press, well after render().
 */
const QUIZ_TARGETS = [1, 4, 6];
const PHRASE_LENGTH = MOCK_MNEMONIC.split(' ').length;

function installDeterministicQuiz() {
  const queue = QUIZ_TARGETS.map((pos) => pos / PHRASE_LENGTH);
  jest
    .spyOn(Math, 'random')
    .mockImplementation(() => (queue.length > 0 ? queue.shift()! : 0));
}

/** Press the button with the given text in the most recent Alert.alert call. */
function pressAlertButton(label: string) {
  const spy = Alert.alert as unknown as jest.Mock;
  const calls = spy.mock.calls;
  const buttons = calls[calls.length - 1][2] as {
    text: string;
    onPress?: () => void;
  }[];
  const button = buttons.find((b) => b.text === label);
  expect(button).toBeDefined();
  act(() => {
    button!.onPress?.();
  });
}

beforeEach(() => {
  jest.spyOn(Alert, 'alert').mockImplementation(() => {});
  installDeterministicQuiz();
});

afterEach(() => {
  jest.restoreAllMocks();
});

describe('CreateWalletScreen — verification carrier (DR-11)', () => {
  it('navigates with backupVerified: true after passing the quiz', () => {
    const navigation = makeNavigation();
    const screen = render(
      <CreateWalletScreen navigation={navigation as never} />
    );

    // Step 1: the phrase is shown; there is no direct route onward.
    expect(screen.getByTestId('mnemonic-display')).toHaveTextContent(
      MOCK_MNEMONIC
    );
    expect(navigation.navigate).not.toHaveBeenCalled();

    // Step 2: enter the quiz. The old self-attestation dialog is gone.
    fireEvent.press(screen.getByTestId('saved-phrase-button'));
    expect(navigation.navigate).not.toHaveBeenCalled();

    for (const index of QUIZ_TARGETS) {
      fireEvent.press(
        screen.getByTestId(`create-wallet-verification-option-${index}`)
      );
    }
    fireEvent.press(screen.getByTestId('create-wallet-verification-verify'));

    expect(navigation.navigate).toHaveBeenCalledTimes(1);
    expect(navigation.navigate).toHaveBeenCalledWith('SecuritySetup', {
      mnemonic: MOCK_MNEMONIC,
      source: 'create',
      backupVerified: true,
    });
  });

  it('navigates with backupVerified: false when the user skips', () => {
    const navigation = makeNavigation();
    const screen = render(
      <CreateWalletScreen navigation={navigation as never} />
    );

    fireEvent.press(screen.getByTestId('saved-phrase-button'));
    fireEvent.press(screen.getByTestId('create-wallet-verification-skip'));

    // Skipping is confirmed, not silent.
    expect(Alert.alert).toHaveBeenCalled();
    expect(navigation.navigate).not.toHaveBeenCalled();

    pressAlertButton('Skip for now');

    expect(navigation.navigate).toHaveBeenCalledWith('SecuritySetup', {
      mnemonic: MOCK_MNEMONIC,
      source: 'create',
      backupVerified: false,
    });
  });

  it('does not navigate if the skip confirmation is cancelled', () => {
    const navigation = makeNavigation();
    const screen = render(
      <CreateWalletScreen navigation={navigation as never} />
    );

    fireEvent.press(screen.getByTestId('saved-phrase-button'));
    fireEvent.press(screen.getByTestId('create-wallet-verification-skip'));
    pressAlertButton('Cancel');

    expect(navigation.navigate).not.toHaveBeenCalled();
  });
});

describe('CreateWalletScreen — back-path guard (U-10)', () => {
  it('registers a beforeRemove listener so every pop path is covered', () => {
    const navigation = makeNavigation();
    render(<CreateWalletScreen navigation={navigation as never} />);

    expect(navigation.hasBeforeRemoveListener()).toBe(true);
  });

  it('blocks a swipe-back / hardware-back and asks for confirmation', () => {
    const navigation = makeNavigation();
    render(<CreateWalletScreen navigation={navigation as never} />);

    const { prevented } = navigation.emitBeforeRemove();

    expect(prevented).toBe(true);
    expect(Alert.alert).toHaveBeenCalled();
    expect(navigation.dispatch).not.toHaveBeenCalled();
  });

  it('lets the pop through only after the user confirms', () => {
    const navigation = makeNavigation();
    render(<CreateWalletScreen navigation={navigation as never} />);

    const { action } = navigation.emitBeforeRemove();
    pressAlertButton('Go Back');

    expect(navigation.dispatch).toHaveBeenCalledWith(action);
  });

  it('re-arms after returning from SecuritySetup', () => {
    // Skipping sets the "we are leaving on purpose" escape and pushes
    // SecuritySetup, leaving this screen mounted underneath. If the user comes
    // back, a stale escape flag would let the next hardware-back silently
    // discard the phrase.
    const navigation = makeNavigation();
    const screen = render(
      <CreateWalletScreen navigation={navigation as never} />
    );

    fireEvent.press(screen.getByTestId('saved-phrase-button'));
    fireEvent.press(screen.getByTestId('create-wallet-verification-skip'));
    pressAlertButton('Skip for now');
    expect(navigation.navigate).toHaveBeenCalled();

    act(() => navigation.emitFocus());

    const { prevented } = navigation.emitBeforeRemove();
    expect(prevented).toBe(true);
    expect(navigation.dispatch).not.toHaveBeenCalled();
  });

  it('keeps the user on screen when the confirmation is cancelled', () => {
    const navigation = makeNavigation();
    render(<CreateWalletScreen navigation={navigation as never} />);

    navigation.emitBeforeRemove();
    pressAlertButton('Cancel');

    expect(navigation.dispatch).not.toHaveBeenCalled();
  });

  it('header back returns to the phrase from the quiz instead of leaving', () => {
    const navigation = makeNavigation();
    const screen = render(
      <CreateWalletScreen navigation={navigation as never} />
    );

    fireEvent.press(screen.getByTestId('saved-phrase-button'));
    expect(screen.getByTestId('create-wallet-verification-root')).toBeTruthy();

    fireEvent.press(screen.getByTestId('header-back'));

    expect(screen.queryByTestId('create-wallet-verification-root')).toBeNull();
    expect(screen.getByTestId('mnemonic-display')).toBeTruthy();
    expect(navigation.goBack).not.toHaveBeenCalled();
  });
});
